=== UpdraftFund/updraft-frontend-lit-ts/src/lib/campaigns/schema/campaign-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "image": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string",
          "description": "data URL of embedded image"
        },
        "alt": {
          "type": "string",
          "description": "alt text for the image"
        }
      }
    },
    "link": {
      "description": "link that provides more info for participants",
      "type": "string"
    },
    "funding": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string",
            "description": "symbol of a token that will be given away as part of the campaign"
          },
          "amount": {
            "type": "number",
            "description": "amount of the token that will be given away as part of the campaign"
          }
        }
      }
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "maxLength": 30
      },
      "minItems": 1,
      "maxItems": 5
    },
    "active": {
      "type": "boolean"
    }
  },
  "required": ["name", "tags"]
}

=== UpdraftFund/updraft-frontend-lit-ts/src/lib/campaigns/updraft-networks.json
{
  "tags": [
    "updraft",
    "vote",
    "networks"
  ],
  "name": "Updraft Networks",
  "description": "Vote to decide which networks will have UPD liquidity pools and Updraft app support.",
  "link": "https://guide.updraft.fund/updraft/voting/networks",
  "image": {
    "url": "https://www.updraft.fund/assets/updraft-logo-RWOFZEhD.png",
    "alt": "Updraft logo"
  },
  "funding": [
    {
      "token": "UPD",
      "amount": 1000000
    }
  ],
  "active": true
}
